# TODO: receive master folder (name of experiment)
# query:
# path_panspace: "/data/bacteria/experiments/autoencoders/6mer/01_22_2024-2/cross-validation/binary_crossentropy-relu-sigmoid-1-fold"
# dir_fasta: "/data/bacteria/gold-standard-datasets/NCTC3000" # all fasta files inside the folder will be used to query the index
# outdir: "/data/bacteria/tools-evaluation/panspace-c/NCTC3000-2"


# Metric Learning
path_panspace: "/data/bacteria/experiments/metric-learning/6mer/02_13_2024-1/cross-validation/triplet_semihard_loss-leaky_relu-3-fold"
dir_fasta: "/data/bacteria/gold-standard-datasets/FDA-ARGOS" # all fasta files inside the folder will be used to query the index
outdir: "/data/bacteria/tools-evaluation/panspace-metric-learning-4/FDA-ARGOS"
threshold_outlier: 0.027 # 2