name: train
channels:
  - conda-forge
  - anaconda
  - pytorch
  - cleanlab
dependencies:
  - python <= 3.11
  - pandas
  - rich
  - tqdm
  - scikit-learn
  - tensorflow-gpu
  - faiss-gpu
  - pyyaml
  - cleanlab
  - ipykernel
  - jupyterlab
  - pip
  - pip: 
    - rich-argparse
    - complexcgr